export const redesignedShellTestIds = {
  crosslogShell: "crosslog-shell",
  topbar: "topbar",
  commandField: "command-field",
  topbarSync: "topbar-sync",
  topbarAddPane: "topbar-add-pane",
  topbarAddFile: "topbar-add-file",
  topbarAddDirectory: "topbar-add-directory",
  themeVariant: "theme-variant",
  platformChrome: "platform-chrome",
  platformChromeTitle: "platform-chrome-title",
  platformChromeMacosTrafficLights: "platform-chrome-macos-traffic-lights",
  platformChromeWindowsCaptionControls: "platform-chrome-windows-caption-controls",
  platformChromeLinuxCaptionControls: "platform-chrome-linux-caption-controls",
  platformChromeWebTitle: "platform-chrome-web-title",
  activityRail: "activity-rail",
  activityRailSearch: "activity-rail-search",
  activityRailFilter: "activity-rail-filter",
  activityRailPalette: "activity-rail-palette",
  activityRailFiles: "activity-rail-files",
  activityRailBookmark: "activity-rail-bookmark",
  activityRailSettings: "activity-rail-settings",
  settingsSurface: "settings-surface",
  settingsThemeSystem: "settings-theme-system",
  settingsThemeLight: "settings-theme-light",
  settingsThemeDark: "settings-theme-dark",
  paneWorkspace: "pane-workspace",
  emptyWorkspace: "empty-workspace",
  emptyDropZone: "empty-drop-zone",
  emptyOpenSource: "empty-open-source",
  emptyOpenFile: "empty-open-file",
  emptyOpenDirectory: "empty-open-directory",
  workspaceScrollbar: "workspace-scrollbar",
  workspaceScrollbarThumb: "workspace-scrollbar-thumb",
  logPane: "log-pane",
  paneResizeBoundary: "pane-resize-boundary",
  paneHeader: "pane-header",
  paneHeaderClose: "pane-header-close",
  paneHeaderSearch: "pane-header-search",
  paneHeaderOffset: "pane-header-offset",
  paneHeaderLifecycle: "pane-header-lifecycle",
  paneHeaderLive: "pane-header-live",
  paneHeaderDeleted: "pane-header-deleted",
  paneHeaderReplaced: "pane-header-replaced",
  paneHeaderMonitoringUnsupported: "pane-header-monitoring-unsupported",
  paneHeaderError: "pane-header-error",
  paneDeletedStatus: "pane-deleted-status",
  paneHeaderDirectoryTitle: "pane-header-directory-title",
  paneHeaderSelectedFile: "pane-header-selected-file",
  paneHeaderEmptyDirectory: "pane-header-empty-directory",
  paneHeaderDirectoryPrevious: "pane-header-directory-previous",
  paneHeaderDirectoryNext: "pane-header-directory-next",
  logViewport: "log-viewport",
  paneSearchPopover: "pane-search-popover",
  paneSearchField: "pane-search-field",
  paneSearchPrevious: "pane-search-previous",
  paneSearchNext: "pane-search-next",
  paneSearchCaseSensitive: "pane-search-case-sensitive",
  paneSearchRegex: "pane-search-regex",
  paneSearchMatchCount: "pane-search-match-count",
  timeOffsetPopover: "time-offset-popover",
  timeOffsetDays: "time-offset-days",
  timeOffsetHours: "time-offset-hours",
  timeOffsetMinutes: "time-offset-minutes",
  timeOffsetSeconds: "time-offset-seconds",
  timeOffsetMilliseconds: "time-offset-milliseconds",
  timeOffsetApply: "time-offset-apply",
  capabilityLimitations: "capability-limitations",
  statusBar: "status-bar",
  obsoleteWorkspaceToolbar: "obsolete-workspace-toolbar",
  obsoletePaneCopyToolbar: "obsolete-pane-copy-toolbar",
  obsoleteSplitButton: "obsolete-split-button",
  obsoleteResizeDecrease: "obsolete-resize-decrease",
  obsoleteResizeIncrease: "obsolete-resize-increase",
  obsoletePaneReadyFooter: "obsolete-pane-ready-footer",
} as const;

export type RedesignedShellTestId =
  (typeof redesignedShellTestIds)[keyof typeof redesignedShellTestIds];

export const redesignedShellStructuralTestIds = [
  redesignedShellTestIds.crosslogShell,
  redesignedShellTestIds.topbar,
  redesignedShellTestIds.commandField,
  redesignedShellTestIds.activityRail,
  redesignedShellTestIds.paneWorkspace,
  redesignedShellTestIds.logPane,
  redesignedShellTestIds.paneHeader,
  redesignedShellTestIds.logViewport,
  redesignedShellTestIds.paneSearchPopover,
  redesignedShellTestIds.timeOffsetPopover,
  redesignedShellTestIds.statusBar,
] as const satisfies readonly RedesignedShellTestId[];

export const redesignedShellOptionalStructuralTestIds = {
  emptyWorkspace: [
    redesignedShellTestIds.emptyWorkspace,
    redesignedShellTestIds.emptyDropZone,
    redesignedShellTestIds.emptyOpenFile,
    redesignedShellTestIds.emptyOpenDirectory,
  ],
  platformChrome: [
    redesignedShellTestIds.themeVariant,
    redesignedShellTestIds.platformChrome,
    redesignedShellTestIds.platformChromeTitle,
  ],
  paneResize: [redesignedShellTestIds.paneResizeBoundary],
} as const satisfies Record<string, readonly RedesignedShellTestId[]>;

export const redesignedShellObsoleteControlTestIds = [
  redesignedShellTestIds.obsoleteWorkspaceToolbar,
  redesignedShellTestIds.obsoletePaneCopyToolbar,
  redesignedShellTestIds.obsoleteSplitButton,
  redesignedShellTestIds.obsoleteResizeDecrease,
  redesignedShellTestIds.obsoleteResizeIncrease,
  redesignedShellTestIds.obsoletePaneReadyFooter,
] as const satisfies readonly RedesignedShellTestId[];
