export const redesignedShellTestIds = {
  crosslogShell: "crosslog-shell",
  topbar: "topbar",
  commandField: "command-field",
  topbarSync: "topbar-sync",
  topbarAddPane: "topbar-add-pane",
  activityRail: "activity-rail",
  activityRailSearch: "activity-rail-search",
  activityRailFilter: "activity-rail-filter",
  activityRailPalette: "activity-rail-palette",
  activityRailFiles: "activity-rail-files",
  activityRailBookmark: "activity-rail-bookmark",
  activityRailSettings: "activity-rail-settings",
  paneWorkspace: "pane-workspace",
  workspaceScrollbar: "workspace-scrollbar",
  workspaceScrollbarThumb: "workspace-scrollbar-thumb",
  logPane: "log-pane",
  paneHeader: "pane-header",
  paneHeaderClose: "pane-header-close",
  paneHeaderSearch: "pane-header-search",
  paneHeaderOffset: "pane-header-offset",
  paneHeaderDirectoryTitle: "pane-header-directory-title",
  paneHeaderSelectedFile: "pane-header-selected-file",
  paneHeaderEmptyDirectory: "pane-header-empty-directory",
  paneHeaderDirectoryPrevious: "pane-header-directory-previous",
  paneHeaderDirectoryNext: "pane-header-directory-next",
  logViewport: "log-viewport",
  paneSearchPopover: "pane-search-popover",
  paneSearchField: "pane-search-field",
  paneSearchPrevious: "pane-search-previous",
  paneSearchNext: "pane-search-next",
  paneSearchCaseSensitive: "pane-search-case-sensitive",
  paneSearchRegex: "pane-search-regex",
  paneSearchMatchCount: "pane-search-match-count",
  timeOffsetPopover: "time-offset-popover",
  timeOffsetDays: "time-offset-days",
  timeOffsetHours: "time-offset-hours",
  timeOffsetMinutes: "time-offset-minutes",
  timeOffsetSeconds: "time-offset-seconds",
  timeOffsetMilliseconds: "time-offset-milliseconds",
  timeOffsetApply: "time-offset-apply",
  statusBar: "status-bar",
} as const;

export type RedesignedShellTestId =
  (typeof redesignedShellTestIds)[keyof typeof redesignedShellTestIds];

export const redesignedShellStructuralTestIds = [
  redesignedShellTestIds.crosslogShell,
  redesignedShellTestIds.topbar,
  redesignedShellTestIds.commandField,
  redesignedShellTestIds.activityRail,
  redesignedShellTestIds.paneWorkspace,
  redesignedShellTestIds.workspaceScrollbar,
  redesignedShellTestIds.logPane,
  redesignedShellTestIds.paneHeader,
  redesignedShellTestIds.logViewport,
  redesignedShellTestIds.paneSearchPopover,
  redesignedShellTestIds.timeOffsetPopover,
  redesignedShellTestIds.statusBar,
] as const satisfies readonly RedesignedShellTestId[];
